spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://database-1.cfqs5srjjjsq.ap-northeast-2.rds.amazonaws.com:3306/knou?serverTimezone=Asia/Seoul
    username: develop
    password: wlghks0326
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
